# Generated by Django 4.0.5 on 2022-06-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom_frequency',
            field=models.ManyToManyField(through='symptom_checker.DiseaseSymptomFrequency', to='symptom_checker.frequency'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(through='symptom_checker.DiseaseSymptomFrequency', to='symptom_checker.symptom'),
        ),
    ]
